// BreakdownTypes.h
//
#pragma once
#include "XmlLib\DLMacros.h"

enum BreakdownType
{
    Breakdown_Unknown = 0,
    //
    Breakdown_DestinyPoints,
    Breakdown_FatePoints,
    Breakdown_NegativeLevels,
    // abilities
    Breakdown_Strength,
    Breakdown_Dexterity,
    Breakdown_Constitution,
    Breakdown_Intelligence,
    Breakdown_Wisdom,
    Breakdown_Charisma,
    // saves
    Breakdown_SaveFortitude,
    Breakdown_SaveReflex,
    Breakdown_SaveWill,
    Breakdown_SaveEnchantment,
    Breakdown_SaveFear,
    Breakdown_SaveIllusion,
    Breakdown_SavePoison,
    Breakdown_SaveDisease,
    Breakdown_SaveSpell,
    Breakdown_SaveMagic,
    Breakdown_SaveTraps,
    Breakdown_SaveCurse,
    // physical
    Breakdown_ArmorCheckPenalty,
    Breakdown_BAB,
    Breakdown_MovementSpeed,
    Breakdown_Hitpoints,
    Breakdown_ReaperHitpoints,
    Breakdown_FalseLife,
    Breakdown_KiMaximum,
    Breakdown_UnconsciousRange,
    Breakdown_StyleBonusFeats,
    Breakdown_PRR,
    Breakdown_MRR,
    Breakdown_MRRCap,
    Breakdown_AC,
    Breakdown_BonusArmorAC,
    Breakdown_BonusShieldAC,
    Breakdown_DR,
    Breakdown_Dodge,
    Breakdown_DodgeCap,
    Breakdown_DodgeCapTowerShield,
    Breakdown_MaxDexBonus,
    Breakdown_MaxDexBonusShields,
    Breakdown_OffHandAttackBonus,
    Breakdown_DoubleStrike,
    Breakdown_DoublestrikeOffhand,
    Breakdown_DoubleShot,
    Breakdown_Fortification,
    Breakdown_HealingAmplification,
    Breakdown_ImbueDice,
    Breakdown_Immunities,
    Breakdown_NaturalArmor,
    Breakdown_NegativeHealingAmplification,
    Breakdown_RepairAmplification,
    Breakdown_ThreatMelee,
    Breakdown_ThreatRanged,
    Breakdown_ThreatSpell,
    Breakdown_SecondaryShieldBash,
    Breakdown_DodgeBypass,
    Breakdown_FortificationBypass,
    Breakdown_TacticalAssassinate,
    Breakdown_TacticalStunning,
    Breakdown_TacticalSunder,
    Breakdown_TacticalTrap,
    Breakdown_TacticalTrip,
    Breakdown_TacticalStunningShield,
    Breakdown_TacticalGeneral,
    Breakdown_TacticalWands,
    Breakdown_TacticalFear,
    Breakdown_TacticalInnateAttack,
    Breakdown_TacticalBreathWeapon,
    Breakdown_TacticalPoison,
    Breakdown_TacticalRuneArm,
    Breakdown_MissileDeflection,
    Breakdown_MissileDeflectionBypass,
    Breakdown_OverrideBAB,
    Breakdown_Incorporeality,
    Breakdown_Displacement,
    Breakdown_Strikethrough,
    Breakdown_SneakAttackDice,
    Breakdown_SneakAttackDamage,
    Breakdown_SneakAttackAttack,
    Breakdown_SneakAttackRange,
    Breakdown_HelplessDamage,
    Breakdown_HelplessDamageReduction,
    Breakdown_DamageAbilityMultiplier,
    Breakdown_DamageAbilityMultiplierOffhand,
    Breakdown_KiPassive,
    Breakdown_KiHit,
    Breakdown_KiCritical,
    Breakdown_RuneArmChargeRate,
    Breakdown_RuneArmStableCharge,
    // skills
    Breakdown_SkillBalance,
    Breakdown_SkillBluff,
    Breakdown_SkillConcentration,
    Breakdown_SkillDiplomacy,
    Breakdown_SkillDisableDevice,
    Breakdown_SkillHaggle,
    Breakdown_SkillHeal,
    Breakdown_SkillHide,
    Breakdown_SkillIntimidate,
    Breakdown_SkillJump,
    Breakdown_SkillListen,
    Breakdown_SkillMoveSilently,
    Breakdown_SkillOpenLock,
    Breakdown_SkillPerform,
    Breakdown_SkillRepair,
    Breakdown_SkillSearch,
    Breakdown_SkillSpellCraft,
    Breakdown_SkillSpot,
    Breakdown_SkillSwim,
    Breakdown_SkillTumble,
    Breakdown_SkillUMD,
    // magical
    Breakdown_Spellpoints,
    Breakdown_Wildsurge,
    Breakdown_EldritchBlastD6,
    Breakdown_EldritchBlastD8,
    Breakdown_ArcaneSpellfailure,
    Breakdown_ArcaneSpellfailureShields,
    Breakdown_SpellResistance,
    Breakdown_SpellCostReduction,
    Breakdown_Accelerate,
    Breakdown_Eschewmaterials,
    Breakdown_Embolden,
    Breakdown_Empower,
    Breakdown_EmpowerHealing,
    Breakdown_Enlarge,
    Breakdown_Extend,
    Breakdown_Heighten,
    Breakdown_Intensify,
    Breakdown_Maximize,
    Breakdown_Quicken,
    Breakdown_CasterLevel_First,    // Breakdown_CasterLevel_First + class index
    Breakdown_CasterLevel_Last = Breakdown_CasterLevel_First + 50,
    Breakdown_MaxCasterLevel_First,
    Breakdown_MaxCasterLevel_Last = Breakdown_MaxCasterLevel_First + 50,
    Breakdown_CasterLevel_School_Abjuration,
    Breakdown_CasterLevel_School_Conjuration,
    Breakdown_CasterLevel_School_Divination,
    Breakdown_CasterLevel_School_Enchantment,
    Breakdown_CasterLevel_School_Evocation,
    Breakdown_CasterLevel_School_Illusion,
    Breakdown_CasterLevel_School_Necromancy,
    Breakdown_CasterLevel_School_Transmutation,
    Breakdown_MaxCasterLevel_School_Abjuration,
    Breakdown_MaxCasterLevel_School_Conjuration,
    Breakdown_MaxCasterLevel_School_Divination,
    Breakdown_MaxCasterLevel_School_Enchantment,
    Breakdown_MaxCasterLevel_School_Evocation,
    Breakdown_MaxCasterLevel_School_Illusion,
    Breakdown_MaxCasterLevel_School_Necromancy,
    Breakdown_MaxCasterLevel_School_Transmutation,
    Breakdown_SpellPenetration,
    Breakdown_SpellPowerAcid,
    Breakdown_SpellPowerChaos,
    Breakdown_SpellPowerCold,
    Breakdown_SpellPowerElectric,
    Breakdown_SpellPowerEvil,
    Breakdown_SpellPowerFire,
    Breakdown_SpellPowerForce,
    Breakdown_SpellPowerLawful,
    Breakdown_SpellPowerLightAlignment,
    Breakdown_SpellPowerNegative,
    Breakdown_SpellPowerPhysical,
    Breakdown_SpellPowerPositive,
    Breakdown_SpellPowerRepair,
    Breakdown_SpellPowerRust,
    Breakdown_SpellPowerSonic,
    Breakdown_SpellPowerPoison,
    Breakdown_SpellPowerUntyped,
    Breakdown_SpellPowerUniversal,
    Breakdown_SpellCriticalChanceAcid,
    Breakdown_SpellCriticalChanceChaos,
    Breakdown_SpellCriticalChanceLightAlignment,
    Breakdown_SpellCriticalChanceCold,
    Breakdown_SpellCriticalChanceElectric,
    Breakdown_SpellCriticalChanceEvil,
    Breakdown_SpellCriticalChanceFire,
    Breakdown_SpellCriticalChanceForce,
    Breakdown_SpellCriticalChanceLawful,
    Breakdown_SpellCriticalChanceNegative,
    Breakdown_SpellCriticalChancePhysical,
    Breakdown_SpellCriticalChancePoison,
    Breakdown_SpellCriticalChancePositive,
    Breakdown_SpellCriticalChanceRepair,
    Breakdown_SpellCriticalChanceRust,
    Breakdown_SpellCriticalChanceSonic,
    Breakdown_SpellCriticalChanceUntyped,
    Breakdown_SpellCriticalChanceUniversal,
    Breakdown_SpellCriticalMultiplierAcid,
    Breakdown_SpellCriticalMultiplierChaos,
    Breakdown_SpellCriticalMultiplierLightAlignment,
    Breakdown_SpellCriticalMultiplierCold,
    Breakdown_SpellCriticalMultiplierElectric,
    Breakdown_SpellCriticalMultiplierEvil,
    Breakdown_SpellCriticalMultiplierFire,
    Breakdown_SpellCriticalMultiplierForce,
    Breakdown_SpellCriticalMultiplierLawful,
    Breakdown_SpellCriticalMultiplierNegative,
    Breakdown_SpellCriticalMultiplierPhysical,
    Breakdown_SpellCriticalMultiplierPoison,
    Breakdown_SpellCriticalMultiplierPositive,
    Breakdown_SpellCriticalMultiplierRepair,
    Breakdown_SpellCriticalMultiplierRust,
    Breakdown_SpellCriticalMultiplierSonic,
    Breakdown_SpellCriticalMultiplierUntyped,
    Breakdown_SpellCriticalMultiplierUniversal,
    Breakdown_SpellSchoolAbjuration,
    Breakdown_SpellSchoolConjuration,
    Breakdown_SpellSchoolDivination,
    Breakdown_SpellSchoolEnchantment,
    Breakdown_SpellSchoolEvocation,
    Breakdown_SpellSchoolIllusion,
    Breakdown_SpellSchoolNecromancy,
    Breakdown_SpellSchoolTransmutation,
    Breakdown_SpellSchoolFear,
    Breakdown_SpellSchoolGlobalDC,
    Breakdown_SpellSchoolRuneArm,
    Breakdown_ImplementInYourHands,
    // songs
    Breakdown_SongCount,
    Breakdown_SongDuration,
    Breakdown_SongACBonus,
    Breakdown_SongDodgeBonus,
    Breakdown_SongSaveBonus,
    Breakdown_SongAttackBonus,
    Breakdown_SongDamageBonus,
    Breakdown_SongDoublestrike,
    Breakdown_SongDoubleshot,
    Breakdown_SongUniversalSpellPower,
    Breakdown_SongSpellPenetration,
    Breakdown_SongCasterLevel,
    Breakdown_SongSkillBonus,
    Breakdown_SongPRR,
    Breakdown_SongMRR,
    Breakdown_SongHealingAmp,
    Breakdown_SongNegativeHealingAmp,
    Breakdown_SongRepairAmp,
    // other
    Breakdown_EnergyResistanceAcid,
    Breakdown_EnergyResistanceChaos,
    Breakdown_EnergyResistanceCold,
    Breakdown_EnergyResistanceElectric,
    Breakdown_EnergyResistanceEvil,
    Breakdown_EnergyResistanceFire,
    Breakdown_EnergyResistanceForce,
    Breakdown_EnergyResistanceGood,
    Breakdown_EnergyResistanceLawful,
    Breakdown_EnergyResistanceLight,
    Breakdown_EnergyResistanceNegative,
    Breakdown_EnergyResistancePoison,
    //Breakdown_EnergyResistancePositive,
    //Breakdown_EnergyResistanceRepair,
    //Breakdown_EnergyResistanceRust,
    Breakdown_EnergyResistanceSonic,
    Breakdown_EnergyAbsorptionAcid,
    Breakdown_EnergyAbsorptionChaos,
    Breakdown_EnergyAbsorptionCold,
    Breakdown_EnergyAbsorptionElectric,
    Breakdown_EnergyAbsorptionEvil,
    Breakdown_EnergyAbsorptionFire,
    Breakdown_EnergyAbsorptionForce,
    Breakdown_EnergyAbsorptionGood,
    Breakdown_EnergyAbsorptionLawful,
    Breakdown_EnergyAbsorptionLight,
    Breakdown_EnergyAbsorptionNegative,
    Breakdown_EnergyAbsorptionPoison,
    //Breakdown_EnergyAbsorptionPositive,
    //Breakdown_EnergyAbsorptionRepair,
    //Breakdown_EnergyAbsorptionRust,
    Breakdown_EnergyAbsorptionSonic,
    // melee power
    Breakdown_MeleePower,
    Breakdown_RangedPower,
    // Enhancements with charges
    Breakdown_LayOnHands,
    Breakdown_Rages,
    Breakdown_TumbleCharges,
    // others
    Breakdown_LOHRegenerationRate,
    // hirelings
    Breakdown_HirelingAbilityBonus,
    Breakdown_HirelingHitpoints,
    Breakdown_HirelingFortification,
    Breakdown_HirelingPRR,
    Breakdown_HirelingMRR,
    Breakdown_HirelingDodge,
    Breakdown_HirelingMeleePower,
    Breakdown_HirelingRangedPower,
    Breakdown_HirelingSpellPower,
    Breakdown_HirelingConcealment,
    // Turn Undead
    Breakdown_TurnUndeadLevel,
    Breakdown_TurnUndeadHitDice,
    // marker, not used as a real breakdown
    Breakdown_EndOfNormalBreakdowns,
    // weapon breakdowns
    Breakdown_WeaponEffectHolder,
    Breakdown_Weapon,
    Breakdown_WeaponEnchantment,
    Breakdown_WeaponBaseDamage,
    Breakdown_WeaponAttackBonus,
    Breakdown_WeaponDamageBonus,
    Breakdown_WeaponOtherDamageEffects,
    Breakdown_WeaponVorpalRange,
    Breakdown_WeaponCriticalThreatRange,
    Breakdown_WeaponCriticalAttackBonus,
    Breakdown_WeaponCriticalDamageBonus,
    Breakdown_WeaponCriticalOtherDamageEffects,
    Breakdown_WeaponCriticalMultiplier,
    Breakdown_WeaponCriticalMultiplier19To20,
    Breakdown_WeaponAttackSpeed,
    Breakdown_WeaponGhostTouch,
    Breakdown_WeaponTrueSeeing,
    Breakdown_DRBypass,
    Breakdown_MainHand,
    Breakdown_OffHand,
};

// this list if not exhaustive. it only contains those items I believe users would like to see
// the bonuses listed for in the Bonuses Pane.
const XmlLib::enumMapEntry<BreakdownType> breakdownNameMap[] =
{
    {Breakdown_Strength, L"Strength"},
    {Breakdown_Dexterity, L"Dexterity"},
    {Breakdown_Constitution, L"Constitution"},
    {Breakdown_Intelligence, L"Intelligence"},
    {Breakdown_Wisdom, L"Wisdom"},
    {Breakdown_Charisma, L"Charisma"},
    {Breakdown_SaveFortitude, L"Fortitude Save"},
    {Breakdown_SaveReflex, L"Reflex Save"},
    {Breakdown_SaveWill, L"Will Save"},
    {Breakdown_PRR, L"PRR"},
    {Breakdown_MRR, L"MRR"},
    {Breakdown_Dodge, L"Dodge"},
    {Breakdown_DoubleStrike, L"Doublestrike"},
    {Breakdown_DoubleShot, L"Doubleshot"},
    {Breakdown_Fortification, L"Fortification"},
    {Breakdown_HealingAmplification, L"Healing Amplification"},
    {Breakdown_NegativeHealingAmplification, L"Negative Healing Amplification"},
    {Breakdown_RepairAmplification, L"Repair Amplification"},
    {Breakdown_ThreatMelee, L"Melee Threat"},
    {Breakdown_ThreatRanged, L"Ranged Threat"},
    {Breakdown_ThreatSpell, L"Spell Threat"},
    {Breakdown_FortificationBypass, L"Fortification Bypass"},
    {Breakdown_TacticalAssassinate, L"Assassinate"},
    {Breakdown_TacticalStunning, L"Stun"},
    {Breakdown_TacticalSunder, L"Sunder"},
    {Breakdown_TacticalTrip, L"Trip"},
    {Breakdown_SneakAttackDice, L"Sneak Attack Dice"},
    {Breakdown_SneakAttackDamage, L"Sneak Attack Damage"},
    {Breakdown_SneakAttackAttack, L"Sneak Attack Attack"},
    {Breakdown_HelplessDamage, L"Helpless Damage Bonus"},
    {Breakdown_SkillBalance, L"Balance"},
    {Breakdown_SkillBluff, L"Bluff"},
    {Breakdown_SkillConcentration, L"Concentration"},
    {Breakdown_SkillDiplomacy, L"Diplomacy"},
    {Breakdown_SkillDisableDevice, L"Disable Device"},
    {Breakdown_SkillHaggle, L"Haggle"},
    {Breakdown_SkillHeal, L"Heal"},
    {Breakdown_SkillHide, L"Hide"},
    {Breakdown_SkillIntimidate, L"Intimidate"},
    {Breakdown_SkillJump, L"Jump"},
    {Breakdown_SkillListen, L"Listen"},
    {Breakdown_SkillMoveSilently, L"Move Silently"},
    {Breakdown_SkillOpenLock, L"Open Lock"},
    {Breakdown_SkillPerform, L"Perform"},
    {Breakdown_SkillRepair, L"Repair"},
    {Breakdown_SkillSearch, L"Search"},
    {Breakdown_SkillSpellCraft, L"Spell Craft"},
    {Breakdown_SkillSpot, L"Spot"},
    {Breakdown_SkillSwim, L"Swim"},
    {Breakdown_SkillTumble, L"Tumble"},
    {Breakdown_SkillUMD, L"Use Magic Device"},
    {Breakdown_Spellpoints, L"Spell Points"},
    {Breakdown_SpellResistance, L"Spell Resistance"},
    {Breakdown_SpellPenetration, L"Spell Penetration"},
    {Breakdown_SpellPowerAcid, L"Acid Spell Power"},
    {Breakdown_SpellPowerChaos, L"Chaos Spell Power"},
    {Breakdown_SpellPowerCold, L"Cold Spell Power"},
    {Breakdown_SpellPowerElectric, L"Electric Spell Power"},
    {Breakdown_SpellPowerEvil, L"Evil Spell Power"},
    {Breakdown_SpellPowerFire, L"Fire Spell Power"},
    {Breakdown_SpellPowerForce, L"Force Spell Power"},
    {Breakdown_SpellPowerLawful, L"Lawful Spell Power"},
    {Breakdown_SpellPowerLightAlignment, L"Light and Alignment Spell Power"},
    {Breakdown_SpellPowerNegative, L"Negative Spell Power"},
    {Breakdown_SpellPowerPhysical, L"Physical Spell Power"},
    {Breakdown_SpellPowerPositive, L"Positive Spell Power"},
    {Breakdown_SpellPowerRepair, L"Repair Spell Power"},
    {Breakdown_SpellPowerRust, L"Rust Spell Power"},
    {Breakdown_SpellPowerSonic, L"Sonic Spell Power"},
    {Breakdown_SpellPowerPoison, L"Poison Spell Power"},
    {Breakdown_SpellPowerUntyped, L"Untyped Spell Power"},
    {Breakdown_SpellPowerUniversal, L"Universal Spell Power"},
    {Breakdown_SpellCriticalChanceAcid, L"Acid Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceChaos, L"Chaos Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceLightAlignment, L"Light and Alignment Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceCold, L"Cold Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceElectric, L"Electric Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceEvil, L"Evil Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceFire, L"Fire Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceForce, L"Force Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceLawful, L"Lawful Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceNegative, L"Negative Spell Critical Chance"},
    {Breakdown_SpellCriticalChancePhysical, L"Physical Spell Critical Chance"},
    {Breakdown_SpellCriticalChancePoison, L"Poison Spell Critical Chance"},
    {Breakdown_SpellCriticalChancePositive, L"Positive Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceRepair, L"Repair Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceRust, L"Rust Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceSonic, L"Sonic Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceUntyped, L"Untyped Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceUniversal, L"Universal Spell Critical Chance"},
    {Breakdown_SpellSchoolAbjuration, L"Abjuration DC"},
    {Breakdown_SpellSchoolConjuration, L"Conjuration DC"},
    {Breakdown_SpellSchoolDivination, L"Divination DC"},
    {Breakdown_SpellSchoolEnchantment, L"Enchantment DC"},
    {Breakdown_SpellSchoolEvocation, L"Evocation DC"},
    {Breakdown_SpellSchoolIllusion, L"Illusion DC"},
    {Breakdown_SpellSchoolNecromancy, L"Necromancy DC"},
    {Breakdown_SpellSchoolTransmutation, L"Transmutation DC"},
    {Breakdown_EnergyResistanceAcid, L"Acid Resistance"},
    {Breakdown_EnergyResistanceChaos, L"Chaos Resistance"},
    {Breakdown_EnergyResistanceCold, L"Cold Resistance"},
    {Breakdown_EnergyResistanceElectric, L"Electric Resistance"},
    {Breakdown_EnergyResistanceEvil, L"Evil Resistance"},
    {Breakdown_EnergyResistanceFire, L"Fire Resistance"},
    {Breakdown_EnergyResistanceForce, L"Force Resistance"},
    {Breakdown_EnergyResistanceGood, L"Good Resistance"},
    {Breakdown_EnergyResistanceLawful, L"Lawful Resistance"},
    {Breakdown_EnergyResistanceLight, L"Light Resistance"},
    {Breakdown_EnergyResistanceNegative, L"Negative Resistance"},
    {Breakdown_EnergyResistancePoison, L"Poison Resistance"},
    {Breakdown_EnergyAbsorptionAcid, L"Acid Absorption"},
    {Breakdown_EnergyAbsorptionChaos, L"Chaos Absorption"},
    {Breakdown_EnergyAbsorptionCold, L"Cold Absorption"},
    {Breakdown_EnergyAbsorptionElectric, L"Electric Absorption"},
    {Breakdown_EnergyAbsorptionEvil, L"Evil Absorption"},
    {Breakdown_EnergyAbsorptionFire, L"Fire Absorption"},
    {Breakdown_EnergyAbsorptionForce, L"Force Absorption"},
    {Breakdown_EnergyAbsorptionGood, L"Good Absorption"},
    {Breakdown_EnergyAbsorptionLawful, L"Lawful Absorption"},
    {Breakdown_EnergyAbsorptionLight, L"Light Absorption"},
    {Breakdown_EnergyAbsorptionNegative, L"Negative Absorption"},
    {Breakdown_EnergyAbsorptionPoison, L"Poison Absorption"},
    {Breakdown_EnergyAbsorptionSonic, L"Sonic Absorption"},
    {Breakdown_MeleePower, L"Melee Power"},
    {Breakdown_RangedPower, L"Ranged Power"},
    {BreakdownType(0), NULL}
};


// this list if not exhaustive. it only contains those items I believe users would like to see
// the bonuses listed for in the Bonuses Pane.
const XmlLib::enumMapEntry<BreakdownType> breakdownMenuMap[] =
{
    {Breakdown_Strength, L"Ability"},
    {Breakdown_Dexterity, L"Ability"},
    {Breakdown_Constitution, L"Ability"},
    {Breakdown_Intelligence, L"Ability"},
    {Breakdown_Wisdom, L"Ability"},
    {Breakdown_Charisma, L"Ability"},

    {Breakdown_SaveFortitude, L"Saves"},
    {Breakdown_SaveReflex, L"Saves"},
    {Breakdown_SaveWill, L"Saves"},

    {Breakdown_PRR, L"Defensive"},
    {Breakdown_MRR, L"Defensive"},
    {Breakdown_Dodge, L"Defensive"},
    {Breakdown_Fortification, L"Defensive"},
    {Breakdown_HealingAmplification, L"Defensive"},
    {Breakdown_NegativeHealingAmplification, L"Defensive"},
    {Breakdown_RepairAmplification, L"Defensive"},

    {Breakdown_DoubleStrike, L"Offensive"},
    {Breakdown_MeleePower, L"Offensive"},
    {Breakdown_ThreatMelee, L"Offensive"},
    {Breakdown_ThreatRanged, L"Offensive"},
    {Breakdown_RangedPower, L"Offensive"},
    {Breakdown_DoubleShot, L"Offensive"},

    {Breakdown_FortificationBypass, L"Offensive"},
    {Breakdown_HelplessDamage, L"Offensive"},

    {Breakdown_TacticalAssassinate, L"Tactical"},
    {Breakdown_TacticalStunning, L"Tactical"},
    {Breakdown_TacticalSunder, L"Tactical"},
    {Breakdown_TacticalTrip, L"Tactical"},
    {Breakdown_SneakAttackDice, L"Sneak Attack"},
    {Breakdown_SneakAttackDamage, L"Sneak Attack"},
    {Breakdown_SneakAttackAttack, L"Sneak Attack"},

    {Breakdown_SkillBalance, L"Skill"},
    {Breakdown_SkillBluff, L"Skill"},
    {Breakdown_SkillConcentration, L"Skill"},
    {Breakdown_SkillDiplomacy, L"Skill"},
    {Breakdown_SkillDisableDevice, L"Skill"},
    {Breakdown_SkillHaggle, L"Skill"},
    {Breakdown_SkillHeal, L"Skill"},
    {Breakdown_SkillHide, L"Skill"},
    {Breakdown_SkillIntimidate, L"Skill"},
    {Breakdown_SkillJump, L"Skill"},
    {Breakdown_SkillListen, L"Skill"},
    {Breakdown_SkillMoveSilently, L"Skill"},
    {Breakdown_SkillOpenLock, L"Skill"},
    {Breakdown_SkillPerform, L"Skill"},
    {Breakdown_SkillRepair, L"Skill"},
    {Breakdown_SkillSearch, L"Skill"},
    {Breakdown_SkillSpellCraft, L"Skill"},
    {Breakdown_SkillSpot, L"Skill"},
    {Breakdown_SkillSwim, L"Skill"},
    {Breakdown_SkillTumble, L"Skill"},
    {Breakdown_SkillUMD, L"Skill"},

    {Breakdown_ThreatSpell, L"Magical"},
    {Breakdown_Spellpoints, L"Magical"},
    {Breakdown_SpellResistance, L"Magical"},
    {Breakdown_SpellPenetration, L"Magical"},

    {Breakdown_SpellPowerAcid, L"Spell Power"},
    {Breakdown_SpellPowerChaos, L"Spell Power"},
    {Breakdown_SpellPowerCold, L"Spell Power"},
    {Breakdown_SpellPowerElectric, L"Spell Power"},
    {Breakdown_SpellPowerEvil, L"Spell Power"},
    {Breakdown_SpellPowerFire, L"Spell Power"},
    {Breakdown_SpellPowerForce, L"Spell Power"},
    {Breakdown_SpellPowerLawful, L"Spell Power"},
    {Breakdown_SpellPowerLightAlignment, L"Spell Power"},
    {Breakdown_SpellPowerNegative, L"Spell Power"},
    {Breakdown_SpellPowerPhysical, L"Spell Power"},
    {Breakdown_SpellPowerPositive, L"Spell Power"},
    {Breakdown_SpellPowerRepair, L"Spell Power"},
    {Breakdown_SpellPowerRust, L"Spell Power"},
    {Breakdown_SpellPowerSonic, L"Spell Power"},
    {Breakdown_SpellPowerPoison, L"Spell Power"},
    {Breakdown_SpellPowerUntyped, L"Spell Power"},
    {Breakdown_SpellPowerUniversal, L"Spell Power"},

    {Breakdown_SpellCriticalChanceAcid, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceChaos, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceLightAlignment, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceCold, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceElectric, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceEvil, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceFire, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceForce, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceLawful, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceNegative, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChancePhysical, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChancePoison, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChancePositive, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceRepair, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceRust, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceSonic, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceUntyped, L"Spell Critical Chance"},
    {Breakdown_SpellCriticalChanceUniversal, L"Spell Critical Chance"},

    {Breakdown_SpellSchoolAbjuration, L"School DC"},
    {Breakdown_SpellSchoolConjuration, L"School DC"},
    {Breakdown_SpellSchoolDivination, L"School DC"},
    {Breakdown_SpellSchoolEnchantment, L"School DC"},
    {Breakdown_SpellSchoolEvocation, L"School DC"},
    {Breakdown_SpellSchoolIllusion, L"School DC"},
    {Breakdown_SpellSchoolNecromancy, L"School DC"},
    {Breakdown_SpellSchoolTransmutation, L"School DC"},

    {Breakdown_EnergyResistanceAcid, L"Energy Resistance"},
    {Breakdown_EnergyResistanceChaos, L"Energy Resistance"},
    {Breakdown_EnergyResistanceCold, L"Energy Resistance"},
    {Breakdown_EnergyResistanceElectric, L"Energy Resistance"},
    {Breakdown_EnergyResistanceEvil, L"Energy Resistance"},
    {Breakdown_EnergyResistanceFire, L"Energy Resistance"},
    {Breakdown_EnergyResistanceForce, L"Energy Resistance"},
    {Breakdown_EnergyResistanceGood, L"Energy Resistance"},
    {Breakdown_EnergyResistanceLawful, L"Energy Resistance"},
    {Breakdown_EnergyResistanceLight, L"Energy Resistance"},
    {Breakdown_EnergyResistanceNegative, L"Energy Resistance"},
    {Breakdown_EnergyResistancePoison, L"Energy Resistance"},

    {Breakdown_EnergyAbsorptionAcid, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionChaos, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionCold, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionElectric, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionEvil, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionFire, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionForce, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionGood, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionLawful, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionLight, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionNegative, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionPoison, L"Energy Absorption"},
    {Breakdown_EnergyAbsorptionSonic, L"Energy Absorption"},
    {BreakdownType(0), NULL}
};
