 
// Commands (ID_* and IDM_*) 
#define HID_STATUSBAR_PANE1                     0x10078
#define HID_STATUSBAR_PANE2                     0x10079
#define HID_VIEW_CUSTOMIZE                      0x1007E
#define HID_GEAR_NEW                            0x100A1
#define HID_GEAR_COPY                           0x100A2
#define HID_GEAR_PASTE                          0x100A3
#define HID_GEAR_DELETE                         0x100A4
#define HID_GEAR_IMPORT                         0x100A5
#define HID_VIEW_NAVIGATION                     0x100B9
#define HID_SET_STYLE                           0x100C9
#define HID_VIEW_APPLOOK_WIN_2000               0x100CD
#define HID_VIEW_APPLOOK_OFF_XP                 0x100CE
#define HID_VIEW_APPLOOK_WIN_XP                 0x100CF
#define HID_VIEW_APPLOOK_OFF_2003               0x100D0
#define HID_VIEW_APPLOOK_VS_2005                0x100D1
#define HID_VIEW_APPLOOK_VS_2008                0x100D2
#define HID_VIEW_APPLOOK_OFF_2007_BLUE          0x100D7
#define HID_VIEW_APPLOOK_OFF_2007_BLACK         0x100D8
#define HID_VIEW_APPLOOK_OFF_2007_SILVER        0x100D9
#define HID_VIEW_APPLOOK_OFF_2007_AQUA          0x100DA
#define HID_VIEW_APPLOOK_WINDOWS_7              0x100DB
#define HID_INVENTORY_UNKNOWN                   0x10834
#define HID_INVENTORY_ARMOR                     0x10835
#define HID_INVENTORY_BELT                      0x10836
#define HID_INVENTORY_BOOTS                     0x10837
#define HID_INVENTORY_BRACERS                   0x10838
#define HID_INVENTORY_CLOAK                     0x10839
#define HID_INVENTORY_GLOVES                    0x1083A
#define HID_INVENTORY_GOGGLES                   0x1083B
#define HID_INVENTORY_HELMET                    0x1083C
#define HID_INVENTORY_NECKLACE                  0x1083D
#define HID_INVENTORY_QUIVER                    0x1083E
#define HID_INVENTORY_RING1                     0x1083F
#define HID_INVENTORY_RING2                     0x10840
#define HID_INVENTORY_TRINKET                   0x10841
#define HID_INVENTORY_WEAPON1                   0x10842
#define HID_INVENTORY_WEAPON2                   0x10843
#define HID_DOCKING_WINDOWS_START               0x10BB8
#define HID_DOCK_LOG                            0x10BB8
#define HID_DOCK_BREAKDOWNS                     0x10BB9
#define HID_DOCK_STANCES                        0x10BBA
#define HID_DOCK_BUILDS                         0x10BBB
#define HID_DOCK_CLASSFEATS                     0x10BBC
#define HID_DOCK_SKILLS                         0x10BBD
#define HID_DOCK_SPECIALFEATS                   0x10BBE
#define HID_DOCK_ENHANCEMENTS                   0x10BBF
#define HID_DOCK_DESTINY                        0x10BC0
#define HID_DOCK_AUTOMATICFEATS                 0x10BC1
#define HID_DOCK_GRANTEDFEATS                   0x10BC2
#define HID_DOCK_REAPERENHANCEMENTS             0x10BC3
#define HID_DOCK_DCS                            0x10BC4
#define HID_DOCK_EQUIPMENT                      0x10BC5
#define HID_DOCK_SPELLS                         0x10BC6
#define HID_DOCK_FAVOR                          0x10BC7
#define HID_DOCK_NOTES                          0x10BC8
#define HID_DOCK_SELFANDPARTYBUFFS              0x10BC9
#define HID_DOCK_UNUSED17                       0x10BCA
#define HID_DOCK_UNUSED18                       0x10BCB
#define HID_DOCK_UNUSED19                       0x10BCC
#define HID_DOCK_UNUSED20                       0x10BCD
#define HID_DOCK_UNUSED21                       0x10BCE
#define HID_DOCK_UNUSED22                       0x10BCF
#define HID_DOCK_UNUSED23                       0x10BD0
#define HID_DOCK_UNUSED24                       0x10BD1
#define HID_DOCK_UNUSED25                       0x10BD2
#define HID_DOCK_UNUSED26                       0x10BD3
#define HID_DOCK_UNUSED27                       0x10BD4
#define HID_DOCK_UNUSED28                       0x10BD5
#define HID_DOCK_UNUSED29                       0x10BD6
#define HID_DOCK_UNUSED30                       0x10BD7
#define HID_DOCKING_WINDOWS_END                 0x10BD7
#define HID_CLASS_PROMPT1                       0x10FA0
#define HID_CLASS_PROMPT2                       0x10FA1
#define HID_CLASS_PROMPT3                       0x10FA2
#define HID_CLASS_PROMPT4                       0x10FA3
#define HID_CLASS_PROMPT5                       0x10FA4
#define HID_CLASS_PROMPT6                       0x10FA5
#define HID_CLASS_PROMPT7                       0x10FA6
#define HID_CLASS_PROMPT8                       0x10FA7
#define HID_CLASS_PROMPT9                       0x10FA8
#define HID_CLASS_PROMPT10                      0x10FA9
#define HID_CLASS_PROMPT11                      0x10FAA
#define HID_CLASS_PROMPT12                      0x10FAB
#define HID_CLASS_PROMPT13                      0x10FAC
#define HID_CLASS_PROMPT14                      0x10FAD
#define HID_CLASS_PROMPT15                      0x10FAE
#define HID_CLASS_PROMPT16                      0x10FAF
#define HID_CLASS_PROMPT17                      0x10FB0
#define HID_CLASS_PROMPT18                      0x10FB1
#define HID_CLASS_PROMPT19                      0x10FB2
#define HID_CLASS_PROMPT20                      0x10FB3
#define HID_CLASS_PROMPT21                      0x10FB4
#define HID_CLASS_PROMPT22                      0x10FB5
#define HID_CLASS_PROMPT23                      0x10FB6
#define HID_CLASS_PROMPT24                      0x10FB7
#define HID_CLASS_PROMPT25                      0x10FB8
#define HID_CLASS_PROMPT26                      0x10FB9
#define HID_CLASS_PROMPT27                      0x10FBA
#define HID_CLASS_PROMPT28                      0x10FBB
#define HID_CLASS_PROMPT29                      0x10FBC
#define HID_CLASS_PROMPT30                      0x10FBD
#define HID_LEVELSELECT_1                       0x18003
#define HID_LEVELSELECT_2                       0x18004
#define HID_LEVELSELECT_3                       0x18005
#define HID_LEVELSELECT_4                       0x18006
#define HID_LEVELSELECT_5                       0x18007
#define HID_LEVELSELECT_6                       0x18008
#define HID_LEVELSELECT_7                       0x18009
#define HID_LEVELSELECT_8                       0x1800A
#define HID_LEVELSELECT_9                       0x1800B
#define HID_LEVELSELECT_10                      0x1800C
#define HID_LEVELSELECT_11                      0x1800D
#define HID_LEVELSELECT_12                      0x1800E
#define HID_LEVELSELECT_13                      0x1800F
#define HID_LEVELSELECT_14                      0x18010
#define HID_LEVELSELECT_15                      0x18011
#define HID_LEVELSELECT_16                      0x18012
#define HID_LEVELSELECT_17                      0x18013
#define HID_LEVELSELECT_18                      0x18014
#define HID_LEVELSELECT_19                      0x18015
#define HID_LEVELSELECT_20                      0x18016
#define HID_LEVELSELECT_21                      0x18017
#define HID_LEVELSELECT_22                      0x18018
#define HID_LEVELSELECT_23                      0x18019
#define HID_LEVELSELECT_24                      0x1801A
#define HID_LEVELSELECT_25                      0x1801B
#define HID_LEVELSELECT_26                      0x1801C
#define HID_LEVELSELECT_27                      0x1801D
#define HID_LEVELSELECT_28                      0x1801E
#define HID_LEVELSELECT_29                      0x1801F
#define HID_LEVELSELECT_30                      0x18020
#define HID_LEVELSELECT_31                      0x18021
#define HID_LEVELSELECT_32                      0x18022
#define HID_LEVELSELECT_33                      0x18023
#define HID_LEVELSELECT_34                      0x18024
#define HID_LEVELSELECT_35                      0x18025
#define HID_LEVELSELECT_36                      0x18026
#define HID_LEVELSELECT_37                      0x18027
#define HID_LEVELSELECT_38                      0x18028
#define HID_LEVELSELECT_39                      0x18029
#define HID_LEVELSELECT_40                      0x1802A
#define HID_DEVELOPMENT_RUNWIKIITEMCRAWLER      0x1802B
#define HID_DEVELOPMENT_PROCESSWIKIFILES        0x1802C
#define HID_LEVELSELECT_SELECTMAXLEVELFORTHISBUILD	0x1802D
#define HID_DEVELOPMENT_UPDATEITEMIMAGES        0x1802E
#define HID_EDIT_COPYLOGTOCLIPBOARD             0x18030
#define HID_DEVELOPMENT_DUMPWEAPONGROUPSTOLOG   0x18031
#define HID_EDIT_CLEARLOG                       0x18032
#define HID_DEVELOPMENT_UPDATEWEAPONITEMIMAGES  0x18033
#define HID_DEVELOPMENT_UPDATEARMORITEMIMAGES   0x18034
#define HID_EDIT_FEATS_EPICONLY                 0x18036
#define HID_EDIT_FEATS_SHOWUNAVAILABLE          0x18037
#define HID_EDIT_IGNORELIST_ACTIVE              0x18038
#define HID_DEVELOPMENT_VERIFYLOADEDDATA        0x18039
#define HID_DEVELOPMENT_PROCESSSPECIFICWIKIFILE 0x1803A
#define HID_SETFAVOR_NONE                       0x1803B
#define HID_SETFAVOR_SOLO                       0x1803C
#define HID_SETFAVOR_CASUAL                     0x1803D
#define HID_SETFAVOR_NORMAL                     0x1803E
#define HID_SETFAVOR_HARD                       0x1803F
#define HID_SETFAVOR_ELITE                      0x18040
#define HID_REAPER_REAPER1                      0x18041
#define HID_REAPER_REAPER2                      0x18042
#define HID_REAPER_REAPER3                      0x18043
#define HID_REAPER_REAPER4                      0x18044
#define HID_REAPER_REAPER5                      0x18045
#define HID_REAPER_REAPER6                      0x18046
#define HID_REAPER_REAPER7                      0x18047
#define HID_REAPER_REAPER8                      0x18048
#define HID_REAPER_REAPER9                      0x18049
#define HID_REAPER_REAPER10                     0x1804A
#define HID_SETFAVOR_SETFAVORLEVEL              0x1804A
#define HID_FILE_IMPORT                         0x1804C
#define HID_DEVELOPMENT_SHOW0VALUEBREAKDOWNENTRIES	0x1804D
#define HID_EDIT_FORUMEXPORT                    0x1804F
#define HID_NOT_SELECTABLE                      0x18050
#define HID_DOCK_SELF                           0x18051
#define HID_LIFE_EXPORTTONEWFILE                0x18052
#define HID_LIFE_COPYTOCLIPBOARD                0x18053
#define HID_LIFE_PASTEFROMCLIPBOARD             0x18054
#define HID_GEAR_IMPORTFROMCLIPBOARD            0x18055
#define HID_LIFE_IMPORTLIVESFROMOTHER           0x18056
 
// Prompts (IDP_*) 
#define HIDP_OLE_INIT_FAILED                    0x30064
 
// Resources (IDR_*) 
#define HIDR_HELP_MENU                          0x20076
#define HIDR_POPUP_EDIT                         0x20077
#define HIDR_MAINFRAME                          0x20080
#define HIDR_MAINFRAME_256                      0x20081
#define HIDR_DDOBuilderTYPE                     0x20082
#define HIDR_OUTPUT_POPUP                       0x200B6
#define HIDR_THEME_MENU                         0x200C8
#define HIDR_LEVEL_SELECT_MENU                  0x2013E
#define HIDR_SELECT_FAVOR_MENU                  0x2014E
#define HIDR_POPUP_MENUS                        0x201A3
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_DDOBUILDER_FORM                    0x20065
#define HIDD_BUILDS_PANE                        0x20066
#define HIDD_CLASS_AND_FEAT_PANE                0x20067
#define HIDD_LOG_PANE                           0x20068
#define HIDD_SKILLS_PANE                        0x20069
#define HIDD_SPECIAL_FEATS_PANE                 0x2006A
#define HIDD_ENHANCEMENTS_PANE                  0x2006B
#define HIDD_ENHANCEMENT_SELECTION              0x2006C
#define HIDD_SELECTION_SELECT_DIALOG            0x2006D
#define HIDD_BREAKDOWNS_PANE                    0x2006E
#define HIDD_STANCES_PANE                       0x2006F
#define HIDD_FEAT_SELECTION                     0x20070
#define HIDD_DESTINY_PANE                       0x20071
#define HIDD_BREAKDOWNS_PANE1                   0x20072
#define HIDD_AUTOMATIC_FEATS_PANE               0x20072
#define HIDD_GRANTED_FEATS_PANE                 0x20073
#define HIDD_REAPER_ENHANCEMENTS_PANE           0x20074
#define HIDD_DC_PANE                            0x20075
#define HIDD_EQUIPMENT_PANE                     0x20076
#define HIDD_INVENTORY_SELECTION                0x2007F
#define HIDD_NAME_GEAR_SET                      0x20083
#define HIDD_SPELLS_PANE                        0x2008B
#define HIDD_SPELLS_PAGE                        0x2008C
#define HIDD_SLA_PAGE                           0x2008E
#define HIDD_FORUM_EXPORT_DIALOG                0x2008F
#define HIDD_FIND_GEAR_DIALOG                   0x20090
#define HIDD_ITEM_SELECT                        0x200DC
#define HIDD_DIALOG_SETITEMIMAGES               0x20141
#define HIDD_FAVOR_PANE                         0x20142
#define HIDD_NOTES_PANE                         0x20143
#define HIDD_SELFANDPARTYBUFFS_PANE             0x2014F
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
